### ISSUE TITLE
Project Not Running

### ISSUE THREAD

**Issue by KaleabTessera** [mldangelo/personal-site#107]
I followed the instructions on how to get the website running, but it doesn't work for my environment.

I followed these steps:
1. yarn
2. cp sample.env .env
3. npm run forever-start 

Step 3 outputs : 
``
forever start --minUptime 1000ms --spinSleepTime 1000ms -a -l forever.log -o out.log -e err.log -c 'nodemon server/server.js --exitcrash --exec babel-node' server/server.js
``

The error logs, have the following:
``
TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/home/kale-abworl/Downloads/Test/mldangelo-master (1)/node_modules/passport-oauth2/lib/strategy.js:82:34)
    at new Strategy (/home/kale-abworl/Downloads/Test/mldangelo-master (1)/node_modules/passport-google-oauth20/lib/strategy.js:52:18)
    at auth (/home/kale-abworl/Downloads/Test/mldangelo-master (1)/server/auth.js:15:16)
    at Object.<anonymous> (/home/kale-abworl/Downloads/Test/mldangelo-master (1)/server/server.js:65:1)
    at Module._compile (module.js:652:30)
    at loader (/home/kale-abworl/Downloads/Test/mldangelo-master (1)/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/kale-abworl/Downloads/Test/mldangelo-master (1)/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at Object.<anonymous> (/home/kale-abworl/Downloads/Test/mldangelo-master (1)/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
/home/kale-abworl/Downloads/Test/mldangelo-master (1)/node_modules/passport-oauth2/lib/strategy.js:82
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
``

Can I turn off the OAuth?

**Comment by mldangelo** [comment]
Hi, sorry for the bug. The following lines should be added to the `sample.env` file:

```bash
GOOGLE_CLIENT_ID=12345
GOOGLE_CLIENT_SECRET=12345
```
You can create credentials for them here: https://console.cloud.google.com/apis/credentials You should configure them like this.  

![client_secret](https://user-images.githubusercontent.com/7235481/45763456-78593680-bbfe-11e8-8b47-b7f589a419db.jpg)

If you would like to disable oauth completely, you will need to remove passport.js To do this:
1. remove `server/auth.js`
2. the associated calls in `server/server.js`
3. the calls to passport.js in `server/routes/index.js`
4. remove `server/models`
5. remove `server/routes/middleware.js` and associated calls in `server/routes/index.js`
6. the private and admin routes from `app/components/Routes/` and associated calls in `app/entry.js` 
7. the admin page in `app/views/admin.js`
8. At this point, you might as well remove all references to mongo as well, and sessions. 
9. Don't forget to modify package.json and yarn.lock eliminating the dependencies you just removed. 

If you would like to run the project without user authentication, I can create a new branch for you that does these things.

**Comment by KaleabTessera** [comment]
Hey man, that would be great! I am just looking for a simple bare bones react template for my cv and your one looks great!

Fyi, after adding the Google ids to env, I still get the following error:
```
[nodemon] starting `babel-node server/server.js`
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/kale-abworl/Downloads/Test/mldangelo1/dist/index.html'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at routes (/home/kale-abworl/Downloads/Test/mldangelo1/server/routes/views/app.js:57:24)
    at routes (/home/kale-abworl/Downloads/Test/mldangelo1/server/routes/index.js:27:3)
    at Object.<anonymous> (/home/kale-abworl/Downloads/Test/mldangelo1/server/server.js:66:1)
    at Module._compile (module.js:652:30)
    at loader (/home/kale-abworl/Downloads/Test/mldangelo1/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/kale-abworl/Downloads/Test/mldangelo1/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at Object.<anonymous> (/home/kale-abworl/Downloads/Test/mldangelo1/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by mldangelo** [comment]
@KaleabTessera I'll work on an update this weekend. To solve your error, set `NODE_ENV=development` and run `npm run dev` to test. I will also change the associated line in `sample.env`. Thank you for testing this for me.

**Comment by mldangelo** [comment]
@KaleabTessera I am in process of removing all login related components here:  https://github.com/mldangelo/mldangelo/tree/remove-login How are you planning on hosting this? Please let me know if you would like me to deprecate the github api and lastfm calls as well so you can host without a server / with github pages.

**Comment by KaleabTessera** [comment]
@mldangelo I am planning on hosting this through AWS, so please deprecate the github api and lastfm calls.

I really appreciate it!

**Comment by mldangelo** [comment]
@KaleabTessera I removed the API calls and configured the branch so that you can host on github for free and deploy with gh-pages by running `npm run deploy`. This will package everything up and write everything to a branch called `gh-pages`. 

You'll want to go to your repository settings at https://github.com/KaleabTessera/mldangelo/settings and configure things like this: 

<img width="774" alt="screen shot 2018-09-24 at 10 25 43 am" src="https://user-images.githubusercontent.com/7235481/45958003-538d0680-bfe4-11e8-978d-743e6c93f050.png">

I would also recommend enabling https.  Please let me know if this is sufficient, or if you need help with anything else.

**Comment by KaleabTessera** [comment]
@mldangelo Thanks a lot Michael! 

I will def have a look at using github pages, I have been using netify to auto deploy and host my builds for free but I will look into github pages. 

Your a rockstar!
