### ISSUE TITLE
npm build not working

### ISSUE THREAD

**Issue by cameronmackinnon** [mldangelo/personal-site#503]
Have been trying to figure out an issue with the node.js CI build for the past few days but having no luck. It seems to be working off and on and I cannot figure out why it works sometimes and sometimes it does not. Most of the time the error from the Node.js CI build looks like what I copied below. The specific page that crashes changes each time (sometimes resume, sometimes contact, etc.). It is always failing on the build portion, but the node-version & os are also random (e.g., sometimes it's mac-os, other times it's ubuntu 18.x).

The local version is working fine. And I've had several successful builds - but then I add a comment, try to build again, and it fails. 

I feel like I've tried everything - uninstalling and reinstalling npm; performing the double npm install; using npm audit fix; re-cloning the original repo instead of using the fork.

I've also had "failed to launch chrome" errors. I took a look at this thread https://github.com/puppeteer/puppeteer/issues/2207 but it doesn't seem to have many solutions. 

If anyone has any insight into what I'm doing wrong, it'd be greatly appreciated! Thanks. 

-------

Run npm run predeploy

> personal-site@4.0.0 predeploy
> npm run build && react-snap

> personal-site@4.0.0 build
> rimraf ./build && react-scripts build

Creating an optimized production build...
One of your dependencies, babel-preset-react-app, is importing the
"@babel/plugin-proposal-private-property-in-object" package without
declaring it in its dependencies. This is currently working because
"@babel/plugin-proposal-private-property-in-object" is already in your
node_modules folder for unrelated reasons, but it may break at any time.

babel-preset-react-app is part of the create-react-app project, which
is not maintianed anymore. It is thus unlikely that this bug will
ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
your devDependencies to work around this error. This will make this message
go away.
  
Compiled successfully.

File sizes after gzip:

  80.2 kB  build/static/js/main.0d7a0995.js
  7.[6](https://github.com/cameronmackinnon/cameronmackinnon.github.io/actions/runs/7522409787/job/20474371646#step:5:7)6 kB  build/static/css/main.d[7](https://github.com/cameronmackinnon/cameronmackinnon.github.io/actions/runs/7522409787/job/20474371646#step:5:8)970cf6.css
  7.64 kB  build/static/js/131.2[8](https://github.com/cameronmackinnon/cameronmackinnon.github.io/actions/runs/7522409787/job/20474371646#step:5:9)2dc151.chunk.js
  6.23 kB  build/static/js/745.4cdb[9](https://github.com/cameronmackinnon/cameronmackinnon.github.io/actions/runs/7522409787/job/20474371646#step:5:10)fc4.chunk.js
  4.73 kB  build/static/js/161.51b6b8a0.chunk.js
  4.36 kB  build/static/js/209.e1f55257.chunk.js
  830 B    build/static/js/[11](https://github.com/cameronmackinnon/cameronmackinnon.github.io/actions/runs/7522409787/job/20474371646#step:5:12)7.6b446b74.chunk.js
  791 B    build/static/js/478.b5e04956.chunk.js
  478 B    build/static/js/964.145423e4.chunk.js
  387 B    build/static/js/922.a9748d02.chunk.js
  153 B    build/static/js/75.954ccb1d.chunk.js
  153 B    build/static/js/625.5982bda3.chunk.js

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  https://cra.link/deployment

✅  crawled 1 out of 6 (/)
✅  crawled 2 out of 6 (/404.html)
✅  crawled 3 out of 7 (/resume)
✅  crawled 4 out of 7 (/about)
✅  crawled 5 out of 7 (/projects)
🔥  error at /resume/resume: Error: Page crashed!
    at Page._onTargetCrashed (/home/runner/work/cameronmackinnon.github.io/cameronmackinnon.github.io/node_modules/puppeteer/lib/Page.js:215:24)
    at CDPSession.<anonymous> (/home/runner/work/cameronmackinnon.github.io/cameronmackinnon.github.io/node_modules/puppeteer/lib/Page.js:[12](https://github.com/cameronmackinnon/cameronmackinnon.github.io/actions/runs/7522409787/job/20474371646#step:5:13)3:56)
    at CDPSession.emit (node:events:517:28)
    at CDPSession._onMessage (/home/runner/work/cameronmackinnon.github.io/cameronmackinnon.github.io/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/home/runner/work/cameronmackinnon.github.io/cameronmackinnon.github.io/node_modules/puppeteer/lib/Connection.js:112:17)
    at WebSocket.<anonymous> (/home/runner/work/cameronmackinnon.github.io/cameronmackinnon.github.io/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
    at WebSocket.onMessage (/home/runner/work/cameronmackinnon.github.io/cameronmackinnon.github.io/node_modules/puppeteer/node_modules/ws/lib/event-target.js:120:[16](https://github.com/cameronmackinnon/cameronmackinnon.github.io/actions/runs/7522409787/job/20474371646#step:5:17))
    at WebSocket.emit (node:events:5[17](https://github.com/cameronmackinnon/cameronmackinnon.github.io/actions/runs/7522409787/job/20474371646#step:5:18):28)
    at Receiver.receiverOnMessage (/home/runner/work/cameronmackinnon.github.io/cameronmackinnon.github.io/node_modules/puppeteer/node_modules/ws/lib/websocket.js:789:[20](https://github.com/cameronmackinnon/cameronmackinnon.github.io/actions/runs/7522409787/job/20474371646#step:5:21))
    at Receiver.emit (node:events:517:[28](https://github.com/cameronmackinnon/cameronmackinnon.github.io/actions/runs/7522409787/job/20474371646#step:5:29))
✅  crawled 6 out of 7 (/contact)

Error: Process completed with exit code 1.

**Comment by atekumulla** [comment]
@cameronmackinnon I'm also having this issue but I'm not experienced in Node.js or Yarn. Have you figured out how to fix this issue? If yes, I'd love to hear the steps you took to change the original configuration so the npm build works.

**Comment by cameronmackinnon** [comment]
@atekumulla I'm pretty confident that it's a memory issue that doesn't have an easy fix. It's only the tests that are failing, but not the actual build, so I've been ignoring it for now as the published version seems to be working fine. The only ideas I had to increase capacity were purchasing more resources through git OR setting up a docker container that has more capacity. You could also turn off some of the tests (e.g., Windows 16.x), but this is more of a work-around than an actual fix.

I'm not experienced in nodejs or yarn either so take this with a grain of salt. Good luck!
