### ISSUE TITLE
Error -86 on npm run predeploy using react-snap with Puppeteer

### ISSUE THREAD

**Issue by anh0001** [mldangelo/personal-site#536]
Running `npm run predeploy` results in an error related to Puppeteer, spawned by `react-snap`. This prevents the static site generation process and shows an `Unknown system error -86` related to the `spawn` call in `child_process`.

## Steps to Reproduce

1. Clone the repo `https://github.com/mldangelo/personal-site`
2. Install dependencies using `npm install`
3. Run `npm run predeploy`
4. See error:

```
Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:761:9)
    at Launcher.launch (/Users/anhar/Codes/personal-site/node_modules/puppeteer/lib/Launcher.js:132:40)
    at async crawl (/Users/anhar/Codes/personal-site/node_modules/react-snap/src/puppeteer_utils.js:188:19)
    at async run (/Users/anhar/Codes/personal-site/node_modules/react-snap/index.js:647:3) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}
```

## Environment

- **OS:** macOS
- **Browser:** Safari
- **Node.js version:** v20.12.2
- **Puppeteer version:** 1.20.0

npm ls puppeteer shows:
```
personal-site@4.0.0 /Users/anhar/Codes/personal-site
└─┬ react-snap@1.23.0
  ├─┬ minimalcss@0.8.1
  │ └── puppeteer@1.20.0 deduped
  └── puppeteer@1.20.0
```

**Comment by anh0001** [comment]
---

Thanks it works! I installed Rosetta 2 using the command:

```
/usr/sbin/softwareupdate --install-rosetta --agree-to-license
```

This resolved the compatibility issues as you suggested. Appreciate your support!

---
